edition = "2018"
# Nightly rustfmt must be used for formatting, e.g. cargo +nightly fmt
unstable_features = true

format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
wrap_comments = true
